{% set name = "scapy" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8f7eb54511c2fab502128ccf18e2e4b98e1f6af6e02ae15b84ad3039143ba3b

build:
  number: 0
  noarch: python
  entry_points:
    - scapy = scapy.main:interact
    - UTscapy = scapy.tools.UTscapy:main
  script: '{{ PYTHON }} -m pip install . --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - ipython
    - cryptography
    - matplotlib-base

test:
  imports:
    - scapy
    - scapy.arch
    - scapy.asn1
    - scapy.contrib
    - scapy.contrib.automotive
    - scapy.contrib.automotive.bmw
    - scapy.contrib.automotive.gm
    - scapy.contrib.automotive.obd
    - scapy.contrib.automotive.obd.iid
    - scapy.contrib.automotive.obd.mid
    - scapy.contrib.automotive.obd.pid
    - scapy.contrib.automotive.obd.tid
    - scapy.contrib.scada
    - scapy.contrib.scada.iec104
    - scapy.layers
    - scapy.layers.tls
    - scapy.layers.tls.crypto
    - scapy.modules
    - scapy.tools
  commands:
    - scapy -h
    - UTscapy -h

about:
  home: https://scapy.net
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE
  summary: 'Scapy: interactive packet manipulation tool'
  description: |
    Scapy is a powerful Python-based interactive packet manipulation program and library.
  doc_url: https://scapy.readthedocs.io
  dev_url: https://github.com/secdev/scapy

extra:
  recipe-maintainers:
    - gpotter2
